apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      resources:
            limits:
              cpu: "1"
              memory: "1000Mi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
      ports:
        - containerPort: 27017
          name: mongodb-port